### ISSUE TITLE
Allow t dependency to be located at different places

### ISSUE THREAD

**Issue by jeparlefrancais** [Frelerik/llama#5]
Hey 👋 

It would be cool if the library was able to find `t` at other places than within the library root itself. That way, I can re-use the same `t` library for Llama and the rest of my project.

If you want I can submit a PR for that, I would do something similar to what I did for my roact animation library `flick`: https://gitlab.com/seaofvoices/flick/-/blob/master/src/FindRoact.lua

I would just wrap each thing that require `t` to require a module script that searches for `t` and then forward it. Let me know if that is something you want 😄

**Comment by freddylist** [comment]
Hi

I agree that it's not very ergonomic for there to be multiple `t` modules in one project. However, I think it's less attractive to have people using `Llama` to have `t` somewhere as well, especially with the release of Luau. Besides, `t` is a very small file, so I think it's fine if `Llama` has its own copy of it. Further, I would like to have as little Roblox-Lua code in `Llama` as possible, so that it may be used in other projects; searching for `t` would break that a little bit.

Hopefully package managers can help in the future!
